language: node_js
node_js:
  - lts/*
install:
  - npm ci
script:
  - npm run build
  - npm test
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run coveralls
    on:
      all_branches: true
      condition: $TRAVIS_BRANCH =~ ^(main|v[0-9]+\.[0-9]+\.[0-9]+)$
  - provider: npm
    email: chris@topher.land
    api_key: $NPM_API_TOKEN
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
      repo: Shakeskeyboarde/slashes
    skip_cleanup: true
  - provider: npm
    email: chris@topher.land
    api_key: $NPM_API_TOKEN
    on:
      all_branches: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-[^[:space:]]+$
      repo: Shakeskeyboarde/slashes
    skip_cleanup: true
    tag: prerelease