name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [current]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Restore
        run: npm ci

      - name: Test
        run: npm test

      - name: Pack
        run: npm pack

      - name: Publish (CodeCov)
        uses: codecov/codecov-action@v3
        with:
          files: ./out/coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      - name: Publish (NPM)
        continue-on-error: true
        run: |
          npm config --location project set //registry.npmjs.org/:_authToken '${NPM_TOKEN}'
          npm publish --access public --ignore-scripts *.tgz
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - name: Create Workspace Artifact
        if: ${{ always() }}
        continue-on-error: true
        run: tar --exclude=workspace.tar -cf workspace.tar .

      - name: Upload Workspace Artifact
        uses: actions/upload-artifact@v3
        if: ${{ always() }}
        continue-on-error: true
        with:
          name: workspace
          path: workspace.tar
          retention-days: 7
